**Setup**
```{r setup}
# Set working directory
library(here)
here()

# Load packages
library(tidyverse)
library("dataRetrieval")
library(dplyr)
library(lubridate)
```

**Load datasets**
*Discharge*
```{r}
# Madison County gauges
### September 2023 - March 2024 (before)
FBR_HotSprings.discharge.before <- readNWISuv(siteNumbers = "03454500",
                                       parameterCd = "00060",
                                       startDate = "2023-09-27", 
                                       endDate = "2024-03-27", 
                                       tz = "America/New_York")
FBR_Marshall.discharge.before <-readNWISuv(siteNumbers = "03453500",
                                       parameterCd = "00060",
                                       startDate = "2023-09-27", 
                                       endDate = "2024-03-27", 
                                       tz = "America/New_York")
### September 2024 - March 2025 (after)
FBR_HotSprings.discharge.after <- readNWISuv(siteNumbers = "03454500",
                                       parameterCd = "00060",
                                       startDate = "2024-09-27", 
                                       endDate = "2025-03-27", 
                                       tz = "America/New_York")

FBR_Marshall.discharge.after <-readNWISuv(siteNumbers = "03453500",
                                       parameterCd = "00060",
                                       startDate = "2024-09-27", 
                                       endDate = "2025-03-27", 
                                       tz = "America/New_York")
## Buncombe County
### September 2023 - March 2024 (before)
FBR_Asheville.discharge.before <- readNWISuv(siteNumbers = "03451500",
                                       parameterCd = "00060",
                                       startDate = "2023-09-27", 
                                       endDate = "2024-03-27", 
                                       tz = "America/New_York")
BeetreeCreek_Swannanoa.discharge.before <- readNWISuv(siteNumbers = "03450000",
                                       parameterCd = "00060",
                                       startDate = "2023-09-27", 
                                       endDate = "2024-03-27", 
                                       tz = "America/New_York")
NFSwannanoa_Walkertown.discharge.before <- readNWISuv(siteNumbers = "0344894205",
                                       parameterCd = "00060",
                                       startDate = "2023-09-27", 
                                       endDate = "2024-03-27", 
                                       tz = "America/New_York")
Swannanoa_Biltmore.discharge.before <- readNWISuv(siteNumbers = "03451000",
                                       parameterCd = "00060",
                                       startDate = "2023-09-27", 
                                       endDate = "2024-03-27", 
                                       tz = "America/New_York")
### September 2024 - March 2025 (after)
FBR_Asheville.discharge.after <- readNWISuv(siteNumbers = "03451500",
                                       parameterCd = "00060",
                                       startDate = "2024-09-27", 
                                       endDate = "2025-03-27", 
                                       tz = "America/New_York")
BeetreeCreek_Swannanoa.discharge.after <- readNWISuv(siteNumbers = "03450000",
                                       parameterCd = "00060",
                                       startDate = "2024-09-27", 
                                       endDate = "2025-03-27", 
                                       tz = "America/New_York")
NFSwannanoa_Walkertown.discharge.after <- readNWISuv(siteNumbers = "0344894205",
                                       parameterCd = "00060",
                                       startDate = "2024-09-27", 
                                       endDate = "2025-03-27", 
                                       tz = "America/New_York")
Swannanoa_Biltmore.discharge.after <- readNWISuv(siteNumbers = "03451000",
                                       parameterCd = "00060",
                                       startDate = "2024-09-27", 
                                       endDate = "2025-03-27", 
                                       tz = "America/New_York")

## Henderson County
### September 2023 - March 2024 (before)
FBR_Fletcher.discharge.before <- readNWISuv(siteNumbers = "03447687",
                                       parameterCd = "00060",
                                       startDate = "2023-09-27", 
                                       endDate = "2024-03-27", 
                                       tz = "America/New_York")
FBR_Blantyre.discharge.before <- readNWISuv(siteNumbers = "03443000",
                                       parameterCd = "00060",
                                       startDate = "2023-09-27", 
                                       endDate = "2024-03-27", 
                                       tz = "America/New_York")
FBR_Rosman.discharge.before <-readNWISuv(siteNumbers = "03439000",
                                       parameterCd = "00060",
                                       startDate = "2023-09-27", 
                                       endDate = "2024-03-27", 
                                       tz = "America/New_York")

### September 2024 - March 2025 (after)
FBR_Fletcher.discharge.after <- readNWISuv(siteNumbers = "03447687",
                                       parameterCd = "00060",
                                       startDate = "2024-09-27", 
                                       endDate = "2025-03-27", 
                                       tz = "America/New_York")
FBR_Blantyre.discharge.after <- readNWISuv(siteNumbers = "03443000",
                                       parameterCd = "00060",
                                       startDate = "2024-09-27", 
                                       endDate = "2025-03-27", 
                                       tz = "America/New_York")
FBR_Rosman.discharge.after <-readNWISuv(siteNumbers = "03439000",
                                       parameterCd = "00060",
                                       startDate = "2024-09-27", 
                                       endDate = "2025-03-27", 
                                       tz = "America/New_York")
```


**Cleanup**
*Discharge*
Rename discharge column and delete unneccesary columnn
```{r}
#Rename column names and delete data qualifier column
## X_00060_00000 to discharge_cfs
FBR_HotSprings.discharge.before <- FBR_HotSprings.discharge.before %>%
  rename(discharge_cfs = X_00060_00000) %>%
  select(-X_00060_00000_cd)

FBR_HotSprings.discharge.after <- FBR_HotSprings.discharge.after %>%
  rename(discharge_cfs = X_00060_00000) %>%
  select(-X_00060_00000_cd)

FBR_Marshall.discharge.before <- FBR_Marshall.discharge.before %>%
  rename(discharge_cfs = X_00060_00000) %>%
  select(-X_00060_00000_cd)
  
FBR_Marshall.discharge.after <- FBR_Marshall.discharge.after %>%
  rename(discharge_cfs = X_00060_00000) %>%
  select(-X_00060_00000_cd)

FBR_Asheville.discharge.before <- FBR_Asheville.discharge.before %>%
  rename(discharge_cfs = X_00060_00000) %>%
  select(-X_00060_00000_cd)

FBR_Asheville.discharge.after <- FBR_Asheville.discharge.after %>%
  rename(discharge_cfs = X_00060_00000) %>%
  select(-X_00060_00000_cd)

BeetreeCreek_Swannanoa.discharge.before <- BeetreeCreek_Swannanoa.discharge.before %>%
  rename(discharge_cfs = X_00060_00000) %>%
  select(-X_00060_00000_cd)

BeetreeCreek_Swannanoa.discharge.after <- BeetreeCreek_Swannanoa.discharge.after %>%
  rename(discharge_cfs = X_00060_00000) %>%
  select(-X_00060_00000_cd)

NFSwannanoa_Walkertown.discharge.before <- NFSwannanoa_Walkertown.discharge.before %>%
  rename(discharge_cfs = X_00060_00000) %>%
  select(-X_00060_00000_cd)

NFSwannanoa_Walkertown.discharge.after <- NFSwannanoa_Walkertown.discharge.after %>%
  rename(discharge_cfs = X_00060_00000) %>%
  select(-X_00060_00000_cd)

Swannanoa_Biltmore.discharge.before <- Swannanoa_Biltmore.discharge.before %>%
  rename(discharge_cfs = X_00060_00000) %>%
  select(-X_00060_00000_cd)

Swannanoa_Biltmore.discharge.after <- Swannanoa_Biltmore.discharge.after %>%
  rename(discharge_cfs = X_00060_00000) %>%
  select(-X_00060_00000_cd)

FBR_Fletcher.discharge.before <- FBR_Fletcher.discharge.before %>%
  rename(discharge_cfs = X_00060_00000) %>%
  select(-X_00060_00000_cd)

FBR_Fletcher.discharge.after <- FBR_Fletcher.discharge.after %>%
  rename(discharge_cfs = X_00060_00000) %>%
  select(-X_00060_00000_cd)

FBR_Blantyre.discharge.before <- FBR_Blantyre.discharge.before %>%
  rename(discharge_cfs = X_00060_00000) %>%
  select(-X_00060_00000_cd)

FBR_Blantyre.discharge.after <- FBR_Blantyre.discharge.after %>%
  rename(discharge_cfs = X_00060_00000) %>%
  select(-X_00060_00000_cd)

FBR_Rosman.discharge.before <- FBR_Rosman.discharge.before %>%
  rename(discharge_cfs = X_00060_00000) %>%
  select(-X_00060_00000_cd)

FBR_Rosman.discharge.after <- FBR_Rosman.discharge.after %>%
  rename(discharge_cfs = X_00060_00000) %>%
  select(-X_00060_00000_cd)
```

Create mean daily discharge datasets for before and after time periods
```{r}
# Create daily discharge dataset using mean
FBR_HotSprings.Dailydischarge.before <- FBR_HotSprings.discharge.before %>%
  mutate(date = as_date(dateTime)) %>% #Extracting date
  group_by(date) %>%
  summarise(mean_daily_discharge_cfs = mean(discharge_cfs, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(time_period = "2023-2024",
         name = "FBR Hot Springs",
         ID_number = "03454500") # creating new columns

FBR_HotSprings.Dailydischarge.after <- FBR_HotSprings.discharge.after %>%
  mutate(date = as_date(dateTime)) %>% #Extracting date
  group_by(date) %>%
  summarise(mean_daily_discharge_cfs = mean(discharge_cfs, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(time_period = "2024-2025",
         name = "FBR Hot Springs",
         ID_number = "03454500") # creating new columns

FBR_Marshall.Dailydischarge.before <- FBR_Marshall.discharge.before %>%
  mutate(date = as_date(dateTime)) %>% #Extracting date
  group_by(date) %>%
  summarise(mean_daily_discharge_cfs = mean(discharge_cfs, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(time_period = "2023-2024",
         name = "FBR Marshall",
         ID_number = "03453500") # creating new columns

FBR_Marshall.Dailydischarge.after <- FBR_Marshall.discharge.after %>%
  mutate(date = as_date(dateTime)) %>% #Extracting date
  group_by(date) %>%
  summarise(mean_daily_discharge_cfs = mean(discharge_cfs, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(time_period = "2024-2025",
         name = "FBR Marshall",
         ID_number = "03453500") # creating new columns)

FBR_Asheville.Dailydischarge.before <- FBR_Asheville.discharge.before %>%
  mutate(date = as_date(dateTime)) %>% #Extracting date
  group_by(date) %>%
  summarise(mean_daily_discharge_cfs = mean(discharge_cfs, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(time_period = "2023-2024",
         name = "FBR_Asheville",
         ID_number = "03451500") # creating new columns
  
FBR_Asheville.Dailydischarge.after <- FBR_Asheville.discharge.after %>%
  mutate(date = as_date(dateTime)) %>% #Extracting date
  group_by(date) %>%
  summarise(mean_daily_discharge_cfs = mean(discharge_cfs, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(time_period = "2024-2025",
         name = "FBR_Asheville",
         ID_number = "03451500") # creating new columns)

BeetreeCreek_Swannanoa.Dailydischarge.before <- BeetreeCreek_Swannanoa.discharge.before %>%
  mutate(date = as_date(dateTime)) %>% #Extracting date
  group_by(date) %>%
  summarise(mean_daily_discharge_cfs = mean(discharge_cfs, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(time_period = "2023-2024",
         name = "Bee_Tree_Creek_Swannanoa",
         ID_number = "03450000") # creating time period column

 BeetreeCreek_Swannanoa.Dailydischarge.after<- BeetreeCreek_Swannanoa.discharge.after %>%
  mutate(date = as_date(dateTime)) %>% #Extracting date
  group_by(date) %>%
  summarise(mean_daily_discharge_cfs = mean(discharge_cfs, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(time_period = "2024-2025",
         name = "Bee_Tree_Creek_Swannanoa",
         ID_number = "03450000") # creating time period column 
 
NFSwannanoa_Walkertown.Dailydischarge.before  <- NFSwannanoa_Walkertown.discharge.before %>%
  mutate(date = as_date(dateTime)) %>% #Extracting date
  group_by(date) %>%
  summarise(mean_daily_discharge_cfs = mean(discharge_cfs, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(time_period = "2023-2024",
         name = "NF_Swannanoa_Walkertown",
         ID_number = "0344894205 ") # creating new columns

NFSwannanoa_Walkertown.Dailydischarge.after <- NFSwannanoa_Walkertown.discharge.after %>%
  mutate(date = as_date(dateTime)) %>% #Extracting date
  group_by(date) %>%
  summarise(mean_daily_discharge_cfs = mean(discharge_cfs, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(time_period = "2024-2025",
         name = "NF_Swannanoa_Walkertown",
         ID_number = "0344894205 ") # creating new columns

Swannanoa_Biltmore.Dailydischarge.before <- Swannanoa_Biltmore.discharge.before %>%
  mutate(date = as_date(dateTime)) %>% #Extracting date
  group_by(date) %>%
  summarise(mean_daily_discharge_cfs = mean(discharge_cfs, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(time_period = "2023-2024",
         name = "Swannanoa_Biltmore",
         ID_number = "03451000") # creating new columns

Swannanoa_Biltmore.Dailydischarge.after <- Swannanoa_Biltmore.discharge.after %>%
  mutate(date = as_date(dateTime)) %>% #Extracting date
  group_by(date) %>%
  summarise(mean_daily_discharge_cfs = mean(discharge_cfs, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(time_period = "2024-2025",
         name = "Swannanoa_Biltmore",
         ID_number = "03451000") # creating new columns

FBR_Fletcher.Dailydischarge.before <- FBR_Fletcher.discharge.before %>%
  mutate(date = as_date(dateTime)) %>% #Extracting date
  group_by(date) %>%
  summarise(mean_daily_discharge_cfs = mean(discharge_cfs, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(time_period = "2023-2024",
         name = "FBR_Fletcher",
         ID_number = "03447687") # creating new columns

FBR_Fletcher.Dailydischarge.after <- FBR_Fletcher.discharge.after %>%
  mutate(date = as_date(dateTime)) %>% #Extracting date
  group_by(date) %>%
  summarise(mean_daily_discharge_cfs = mean(discharge_cfs, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(time_period = "2024-2025",
         name = "FBR_Fletcher",
         ID_number = "03447687") # creating new columns
         
FBR_Blantyre.Dailydischarge.before <- FBR_Blantyre.discharge.before %>%
  mutate(date = as_date(dateTime)) %>% #Extracting date
  group_by(date) %>%
  summarise(mean_daily_discharge_cfs = mean(discharge_cfs, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(time_period = "2023-2024",
         name = "FBR_Blantyre",
         ID_number = "03443000") # creating new columns

FBR_Blantyre.Dailydischarge.after <- FBR_Blantyre.discharge.after %>%
  mutate(date = as_date(dateTime)) %>% #Extracting date
  group_by(date) %>%
  summarise(mean_daily_discharge_cfs = mean(discharge_cfs, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(time_period = "2024-2025",
         name = "FBR_Blantyre",
         ID_number = "03443000") # creating new columns

FBR_Rosman.Dailydischarge.before <- FBR_Rosman.discharge.before %>%
  mutate(date = as_date(dateTime)) %>% #Extracting date
  group_by(date) %>%
  summarise(mean_daily_discharge_cfs = mean(discharge_cfs, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(time_period = "2023-2024",
         name = "FBR_Rosman",
         ID_number = "03439000") # creating new columns

FBR_Rosman.Dailydischarge.after <- FBR_Rosman.discharge.after %>%
  mutate(date = as_date(dateTime)) %>% #Extracting date
  group_by(date) %>%
  summarise(mean_daily_discharge_cfs = mean(discharge_cfs, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(time_period = "2024-2025",
         name = "FBR_Rosman",
         ID_number = "03439000") # creating new columns
```

Create monthly discharge datasets for before and after time periods
```{r}
# Create monthly discharge using mean
FBR_HotSprings.Monthlydischarge.before <- FBR_HotSprings.Dailydischarge.before %>%
  mutate(year = year(date),
         month = month(date)) %>%
  group_by(year,month,time_period,name,ID_number) %>%
  summarise(mean_monthly_discharge_cfs = mean(mean_daily_discharge_cfs, na.rm = TRUE)) %>%
  ungroup()


FBR_HotSprings.Monthlydischarge.after <- FBR_HotSprings.Dailydischarge.after %>%
  mutate(year = year(date),
         month = month(date)) %>%
  group_by(year,month,time_period,name,ID_number) %>%
  summarise(mean_monthly_discharge_cfs = mean(mean_daily_discharge_cfs, na.rm = TRUE)) %>%
  ungroup()


FBR_Marshall.Monthlydischarge.before <- FBR_Marshall.Dailydischarge.before %>%
  mutate(year = year(date),
         month = month(date)) %>%
  group_by(year,month,time_period,name,ID_number) %>%
  summarise(mean_monthly_discharge_cfs = mean(mean_daily_discharge_cfs, na.rm = TRUE)) %>%
  ungroup()

FBR_Marshall.Monthlydischarge.after <- FBR_Marshall.Dailydischarge.after %>%
  mutate(year = year(date),
         month = month(date)) %>%
  group_by(year,month,time_period,name,ID_number) %>%
  summarise(mean_monthly_discharge_cfs = mean(mean_daily_discharge_cfs, na.rm = TRUE)) %>%
  ungroup()

FBR_Asheville.Monthlydischarge.before <- FBR_Asheville.Dailydischarge.before %>%
  mutate(year = year(date),
         month = month(date)) %>%
  group_by(year,month,time_period,name,ID_number) %>%
  summarise(mean_monthly_discharge_cfs = mean(mean_daily_discharge_cfs, na.rm = TRUE)) %>%
  ungroup()

FBR_Asheville.Monthlydischarge.after <- FBR_Asheville.Dailydischarge.after %>%
  mutate(year = year(date),
         month = month(date)) %>%
  group_by(year,month,time_period,name,ID_number) %>%
  summarise(mean_monthly_discharge_cfs = mean(mean_daily_discharge_cfs, na.rm = TRUE)) %>%
  ungroup()

BeetreeCreek_Swannanoa.Monthlydischarge.before <- BeetreeCreek_Swannanoa.Dailydischarge.before %>%
  mutate(year = year(date),
         month = month(date)) %>%
  group_by(year,month,time_period,name,ID_number) %>%
  summarise(mean_monthly_discharge_cfs = mean(mean_daily_discharge_cfs, na.rm = TRUE)) %>%
  ungroup()

BeetreeCreek_Swannanoa.Monthlydischarge.after <- BeetreeCreek_Swannanoa.Dailydischarge.after %>%
  mutate(year = year(date),
         month = month(date)) %>%
  group_by(year,month,time_period,name,ID_number) %>%
  summarise(mean_monthly_discharge_cfs = mean(mean_daily_discharge_cfs, na.rm = TRUE)) %>%
  ungroup()

NFSwannanoa_Walkertown.Monthlydischarge.before <- NFSwannanoa_Walkertown.Dailydischarge.before %>%
  mutate(year = year(date),
         month = month(date)) %>%
  group_by(year,month,time_period,name,ID_number) %>%
  summarise(mean_monthly_discharge_cfs = mean(mean_daily_discharge_cfs, na.rm = TRUE)) %>%
  ungroup()

NFSwannanoa_Walkertown.Monthlydischarge.after <- NFSwannanoa_Walkertown.Dailydischarge.after %>%
  mutate(year = year(date),
         month = month(date)) %>%
  group_by(year,month,time_period,name,ID_number) %>%
  summarise(mean_monthly_discharge_cfs = mean(mean_daily_discharge_cfs, na.rm = TRUE)) %>%
  ungroup()

Swannanoa_Biltmore.Monthlydischarge.before <- Swannanoa_Biltmore.Dailydischarge.before %>%
  mutate(year = year(date),
         month = month(date)) %>%
  group_by(year,month,time_period,name,ID_number) %>%
  summarise(mean_monthly_discharge_cfs = mean(mean_daily_discharge_cfs, na.rm = TRUE)) %>%
  ungroup()

Swannanoa_Biltmore.Monthlydischarge.after <- Swannanoa_Biltmore.Dailydischarge.after %>%
  mutate(year = year(date),
         month = month(date)) %>%
  group_by(year,month,time_period,name,ID_number) %>%
  summarise(mean_monthly_discharge_cfs = mean(mean_daily_discharge_cfs, na.rm = TRUE)) %>%
  ungroup()
  
FBR_Fletcher.Monthlydischarge.before <- FBR_Fletcher.Dailydischarge.before %>%
  mutate(year = year(date),
         month = month(date)) %>%
  group_by(year,month,time_period,name,ID_number) %>%
  summarise(mean_monthly_discharge_cfs = mean(mean_daily_discharge_cfs, na.rm = TRUE)) %>%
  ungroup()

FBR_Fletcher.Monthlydischarge.after <- FBR_Fletcher.Dailydischarge.after %>%
  mutate(year = year(date),
         month = month(date)) %>%
  group_by(year,month,time_period,name,ID_number) %>%
  summarise(mean_monthly_discharge_cfs = mean(mean_daily_discharge_cfs, na.rm = TRUE)) %>%
  ungroup()

FBR_Blantyre.Monthlydischarge.before <- FBR_Blantyre.Dailydischarge.before %>%
  mutate(year = year(date),
         month = month(date)) %>%
  group_by(year,month,time_period,name,ID_number) %>%
  summarise(mean_monthly_discharge_cfs = mean(mean_daily_discharge_cfs, na.rm = TRUE)) %>%
  ungroup()

FBR_Blantyre.Monthlydischarge.after <- FBR_Blantyre.Dailydischarge.after %>%
  mutate(year = year(date),
         month = month(date)) %>%
  group_by(year,month,time_period,name,ID_number) %>%
  summarise(mean_monthly_discharge_cfs = mean(mean_daily_discharge_cfs, na.rm = TRUE)) %>%
  ungroup()

FBR_Rosman.Monthlydischarge.before <- FBR_Rosman.Dailydischarge.before %>%
  mutate(year = year(date),
         month = month(date)) %>%
  group_by(year,month,time_period,name,ID_number) %>%
  summarise(mean_monthly_discharge_cfs = mean(mean_daily_discharge_cfs, na.rm = TRUE)) %>%
  ungroup()

FBR_Rosman.Monthlydischarge.after <- FBR_Rosman.Dailydischarge.after %>%
  mutate(year = year(date),
         month = month(date)) %>%
  group_by(year,month,time_period,name,ID_number) %>%
  summarise(mean_monthly_discharge_cfs = mean(mean_daily_discharge_cfs, na.rm = TRUE)) %>%
  ungroup()

```


*pH*
Can use same workflow as discharge



*Turbidity*
Can use same workflow as discharge
