\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE}
# Set your working directory
library(here)
here()
# Load your packages
library(tidyverse)
library("dataRetrieval")
library(dplyr)
library(lubridate)
# Set your ggplot theme

# Load your datasets

```


# Rationale and Research Questions
Hurricane Helene made landfall in Western North Carolina on September 27th, 2024. It primarily affected the City of Asheville and small towns like Marshall, situated north of Asheville and Swannanoa, situated east of Asheville. The French Broad River runs south-north through the City of Asheville, and the Swannanoa River runs west through Asheville, before joining the French Broad within the city limits. After Helene, it was clear that the two rivers' morphology had changed. Our project examines discharge (cfs) at 10 USGS stream gauges located in the French Broad and Swannanoa rivers. We look at time periods before (Sept. 2023 - March 2024) and after (Sept. 2024 - March 2025) the hurricane to make comparisons about discharge.

This project has 2 research questions:
1. Has the overall discharge (cfs) at 9 Western NC USGS stream gages increased after Hurricane Helene?
2. If there is an increase, is there a long term trend of the increase?

\newpage

# Dataset Information

Our data is from 9 USGS stream gauges in Western NC. We used the USGS R package "dataRetrieval" to pull the stream gauge data. Specifically, we used discharge (parameter code: #00060). We were going to also look at pH (parameter code: #00400) and and turbidity (parameter code: #00076), but quuickly found that pH and turbidity are not measured at our 9 gage locations. We pulled data from September 27, 2023 - March 27, 2023 and September 27 2024 - March 27, 2025.

Link to data: https://waterdata.usgs.gov/state/north-carolina/ 

The 9 USGS stream gages we used are:

- USGS-03454500 | French Broad River at Hot Springs, NC | Madison County, North Carolina
- USGS-03453500 | French Broad River at Marshall, NC| Madison County, North Carolina
- USGS-03451500 | French Broad River at Asheville, NC | Buncombe County, North Carolina
- USGS-03450000 | Beetree Creek Near Swannanoa, NC | Buncombe County, North Carolina
- USGS-0344894205 | North Fork Swannanoa River Near Walkertown, NC |Buncombe County, North Carolina
- USGS-03451000 | Swannanoa River at Biltmore, NC | Buncombe County, North Carolina
- USGS-03447687 | French Broad River Near Fletcher, NC | Henderson County, North Carolina
- USGS-03443000 | French Broad River at Blantyre, NC |Transylvania County, North Carolina
- USGS-03439000 | French Broad River at Rosman, NC | Transylvania County, North Carolina
\newpage

# Exploratory Analysis 



\newpage

# Analysis



## Question 1: <insert specific question here and add additional subsections for additional questions below, if needed>

## Question 2: 




\newpage

# Summary and Conclusions


\newpage

# References
<add references here if relevant, otherwise delete this section> 
