\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE}
# Set your working directory
library(here)
here()
# Load your packages
library(tidyverse)
library("dataRetrieval")
library(dplyr)
library(lubridate)
# Set your ggplot theme

# Load your datasets

```


# Rationale and Research Questions
Hurricane Helene made landfall in Western North Carolina on September 27th, 2024. It primarily affected the City of Asheville and small towns like Marshall, situated north of Asheville and Swannanoa, situated east of Asheville. The French Broad River runs south-north through the City of Asheville, and the Swannanoa River runs west through Asheville, before joining the French Broad within the city limits. After Helene, it was clear that the two rivers' morphology had changed. Our project examines discharge (cfs), turbidity, and pH at 10 USGS stream gauges located in the French Broad and Swannanoa rivers. We look at time periods before (Sept. 2023 - March 2024) and after (Sept. 2024 - March 2024) the hurricane to make comparisons with these variables.

This project has three research questions:
1. Has the overall discharge (cfs) at 10 Western NC USGS stream gauges increased after Hurricane Helene?
2. Has the overall turbidity increased at 10 Western NC USGS stream gauges increased after Hurricane Helene?
3. Has the overall pH at 10 Western NC USGS stream gauges increased after Hurricane Helene?

\newpage

# Dataset Information



\newpage

# Exploratory Analysis 



\newpage

# Analysis



## Question 1: <insert specific question here and add additional subsections for additional questions below, if needed>

## Question 2: 




\newpage

# Summary and Conclusions


\newpage

# References
<add references here if relevant, otherwise delete this section> 
